apiVersion: v1
kind: Service
metadata:
  name: priyanka-image-service
spec:
  selector:
    app: priyanka-image
  ports:
    - protocol: TCP
      port: 80  # Port to expose externally
      targetPort: 8080  # Port your app listens on
  type: LoadBalancer  # Expose the app to the outside world
